using System;
using System.Collections.Generic;
using System.Text;

namespace Transgenesis {
    enum AttributeTypes {
        UNKNOWN,
        UNID,
        TYPE_ANY,
        TYPE_SOUND,
        SCREEN_LOCAL_OR_TYPE,
        TYPE_ARMOR,
        TYPE_IMAGE,
        TYPE_MOD,
        TYPE_SOVEREIGN,
        TYPE_SPACE_ENVIRONMENT,
        TYPE_SYSTEM_MAP,
        TYPE_SYSTEM_TYPE,
        TYPE_INHERITED,
        SYSTEM_PART_TABLE,
        INTEGER,
        INTEGER_SEQUENCE,
        WHOLE,
        WHOLE_100,
        DOUBLE,
        HEX_COLOR,
        HEX_NUMBER,
        STRING,
        FILENAME,
        FILE_JPG,
        FILE_MP3,
        DICE_RANGE,
        RANGE_0_100,
        CHARACTER,
        FREQUENCY,
        PRICE_ADJ,
        TYPE_WEAPON,
        TYPE_EFFECT,
        TYPE_STATION,
        TYPE_ITEM,
        LEVEL_VALUE,
        CURRENCY_VALUE,
        CURRENCY_VALUE_SEQUENCE,
        TYPE_SHIP_TABLE,
        TYPE_DOCKSCREEN,
        TYPE_DEVICE,
        CATEGORY_DEVICE,
        TYPE_OVERLAY,
        OVERLAP_CHECK,
        POINT,
        PARTITION_NODES_ORDER,
        TYPE_SHIPCLASS,
        
    }
}
